<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MarkMello.Infrastructure</RootNamespace>
    <AssemblyName>MarkMello.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="1.3.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Naiad" Version="0.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarkMello.Application\MarkMello.Application.csproj" />
    <ProjectReference Include="..\MarkMello.Domain\MarkMello.Domain.csproj" />
  </ItemGroup>

</Project>
